# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'testgui.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(717, 597)
        MainWindow.setContextMenuPolicy(Qt.CustomContextMenu)
        MainWindow.setSizeGripEnabled(False)
        self.centralwidget = QFrame(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setGeometry(QRect(0, 0, 1021, 611))
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet(u"\n"
"background-color: rgb(33, 37, 43);")
        self.centralwidget.setFrameShape(QFrame.StyledPanel)
        self.centralwidget.setFrameShadow(QFrame.Raised)
        self.titlelabel = QLabel(self.centralwidget)
        self.titlelabel.setObjectName(u"titlelabel")
        self.titlelabel.setGeometry(QRect(260, 10, 221, 51))
        font1 = QFont()
        font1.setFamily(u"MS Gothic")
        font1.setPointSize(24)
        font1.setBold(True)
        font1.setUnderline(False)
        font1.setWeight(75)
        self.titlelabel.setFont(font1)
        self.titlelabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.titlelabel.setAlignment(Qt.AlignCenter)
        self.titlelabel.setIndent(0)
        self.quitButton = QPushButton(self.centralwidget)
        self.quitButton.setObjectName(u"quitButton")
        self.quitButton.setGeometry(QRect(630, 560, 75, 23))
        self.quitButton.setStyleSheet(u"background-color: rgb(202, 202, 202);")
        self.fileencodelabel = QLabel(self.centralwidget)
        self.fileencodelabel.setObjectName(u"fileencodelabel")
        self.fileencodelabel.setGeometry(QRect(40, 80, 161, 51))
        font2 = QFont()
        font2.setFamily(u"MS Gothic")
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setUnderline(False)
        font2.setWeight(75)
        self.fileencodelabel.setFont(font2)
        self.fileencodelabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.fileencodelabel.setTextFormat(Qt.PlainText)
        self.fileencodelabel.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.fileencodelabel.setWordWrap(True)
        self.fileencodelabel.setMargin(0)
        self.fileencodelabel.setIndent(0)
        self.piclabel_3 = QLabel(self.centralwidget)
        self.piclabel_3.setObjectName(u"piclabel_3")
        self.piclabel_3.setGeometry(QRect(40, 170, 221, 51))
        self.piclabel_3.setFont(font2)
        self.piclabel_3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.piclabel_3.setTextFormat(Qt.PlainText)
        self.piclabel_3.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.piclabel_3.setWordWrap(True)
        self.piclabel_3.setMargin(0)
        self.piclabel_3.setIndent(0)
        self.encodeButton = QPushButton(self.centralwidget)
        self.encodeButton.setObjectName(u"encodeButton")
        self.encodeButton.setGeometry(QRect(130, 560, 75, 23))
        self.encodeButton.setStyleSheet(u"background-color: rgb(202, 202, 202);")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(220, 90, 211, 22))
        font3 = QFont()
        font3.setBold(True)
        font3.setWeight(75)
        font3.setKerning(True)
        self.comboBox.setFont(font3)
        self.comboBox.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox.setStyleSheet(u"background-color: rgb(202, 202, 202);\n"
"alternate-background-color: rgb(255, 255, 255);")
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(220, 190, 211, 22))
        self.comboBox_2.setFont(font)
        self.comboBox_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.comboBox_2.setStyleSheet(u"background-color: rgb(202, 202, 202);")
        self.pictureframe = QFrame(self.centralwidget)
        self.pictureframe.setObjectName(u"pictureframe")
        self.pictureframe.setGeometry(QRect(30, 320, 291, 231))
        self.pictureframe.setStyleSheet(u"background-color: rgb(202, 202, 202);")
        self.pictureframe.setFrameShape(QFrame.StyledPanel)
        self.pictureframe.setFrameShadow(QFrame.Raised)
        self.label_before = QLabel(self.pictureframe)
        self.label_before.setObjectName(u"label_before")
        self.label_before.setGeometry(QRect(0, 0, 291, 231))
        self.label_before.setPixmap(QPixmap(u"../../../../Downloads/photo-1553949285-bdcb31ec5cba.jpg"))
        self.label_before.setScaledContents(True)
        self.encodeframe = QFrame(self.centralwidget)
        self.encodeframe.setObjectName(u"encodeframe")
        self.encodeframe.setGeometry(QRect(330, 320, 281, 231))
        self.encodeframe.setStyleSheet(u"background-color: rgb(202, 202, 202);")
        self.encodeframe.setFrameShape(QFrame.StyledPanel)
        self.encodeframe.setFrameShadow(QFrame.Raised)
        self.originalpiclabel = QLabel(self.centralwidget)
        self.originalpiclabel.setObjectName(u"originalpiclabel")
        self.originalpiclabel.setGeometry(QRect(100, 300, 141, 16))
        self.originalpiclabel.setFont(font2)
        self.originalpiclabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.originalpiclabel.setTextFormat(Qt.PlainText)
        self.originalpiclabel.setAlignment(Qt.AlignCenter)
        self.originalpiclabel.setWordWrap(True)
        self.originalpiclabel.setMargin(0)
        self.originalpiclabel.setIndent(0)
        self.encodedpiclabel = QLabel(self.centralwidget)
        self.encodedpiclabel.setObjectName(u"encodedpiclabel")
        self.encodedpiclabel.setGeometry(QRect(400, 300, 141, 20))
        self.encodedpiclabel.setFont(font2)
        self.encodedpiclabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.encodedpiclabel.setTextFormat(Qt.PlainText)
        self.encodedpiclabel.setAlignment(Qt.AlignCenter)
        self.encodedpiclabel.setWordWrap(True)
        self.encodedpiclabel.setMargin(0)
        self.encodedpiclabel.setIndent(0)
        self.txtradioButton = QRadioButton(self.centralwidget)
        self.txtradioButton.setObjectName(u"txtradioButton")
        self.txtradioButton.setGeometry(QRect(500, 90, 101, 17))
        font4 = QFont()
        font4.setFamily(u"MS Gothic")
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setWeight(75)
        self.txtradioButton.setFont(font4)
        self.txtradioButton.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.txtradioButton.setIconSize(QSize(20, 20))
        self.txtradioButton.setChecked(False)
        self.mp4radioButton = QRadioButton(self.centralwidget)
        self.mp4radioButton.setObjectName(u"mp4radioButton")
        self.mp4radioButton.setGeometry(QRect(500, 110, 101, 17))
        self.mp4radioButton.setFont(font4)
        self.mp4radioButton.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.mp4radioButton.setIconSize(QSize(20, 20))
        self.mp4radioButton.setChecked(False)
        self.LSBhorizontalSlider = QSlider(self.centralwidget)
        self.LSBhorizontalSlider.setObjectName(u"LSBhorizontalSlider")
        self.LSBhorizontalSlider.setGeometry(QRect(460, 190, 191, 22))
        font5 = QFont()
        font5.setFamily(u"MS Gothic")
        self.LSBhorizontalSlider.setFont(font5)
        self.LSBhorizontalSlider.setMouseTracking(True)
        self.LSBhorizontalSlider.setAcceptDrops(False)
        self.LSBhorizontalSlider.setAutoFillBackground(False)
        self.LSBhorizontalSlider.setStyleSheet(u"border-color: rgb(0, 0, 0);")
        self.LSBhorizontalSlider.setMaximum(6)
        self.LSBhorizontalSlider.setSingleStep(1)
        self.LSBhorizontalSlider.setValue(0)
        self.LSBhorizontalSlider.setTracking(True)
        self.LSBhorizontalSlider.setOrientation(Qt.Horizontal)
        self.LSBhorizontalSlider.setTickPosition(QSlider.TicksBelow)
        self.LSBhorizontalSlider.setTickInterval(0)
        self.DecodeButton = QPushButton(self.centralwidget)
        self.DecodeButton.setObjectName(u"DecodeButton")
        self.DecodeButton.setGeometry(QRect(440, 560, 75, 23))
        self.DecodeButton.setStyleSheet(u"background-color: rgb(202, 202, 202);")
        self.lsbslidernum0 = QLabel(self.centralwidget)
        self.lsbslidernum0.setObjectName(u"lsbslidernum0")
        self.lsbslidernum0.setGeometry(QRect(450, 220, 31, 16))
        self.lsbslidernum0.setFont(font4)
        self.lsbslidernum0.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lsbslidernum0.setAlignment(Qt.AlignCenter)
        self.lsbslidernum1 = QLabel(self.centralwidget)
        self.lsbslidernum1.setObjectName(u"lsbslidernum1")
        self.lsbslidernum1.setGeometry(QRect(490, 220, 16, 16))
        self.lsbslidernum1.setFont(font4)
        self.lsbslidernum1.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lsbslidernum1.setAlignment(Qt.AlignCenter)
        self.lsbslidernum2 = QLabel(self.centralwidget)
        self.lsbslidernum2.setObjectName(u"lsbslidernum2")
        self.lsbslidernum2.setGeometry(QRect(520, 220, 21, 16))
        self.lsbslidernum2.setFont(font4)
        self.lsbslidernum2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lsbslidernum2.setAlignment(Qt.AlignCenter)
        self.lsbslidernum3 = QLabel(self.centralwidget)
        self.lsbslidernum3.setObjectName(u"lsbslidernum3")
        self.lsbslidernum3.setGeometry(QRect(550, 220, 16, 16))
        self.lsbslidernum3.setFont(font4)
        self.lsbslidernum3.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lsbslidernum3.setAlignment(Qt.AlignCenter)
        self.lsbslidernum5 = QLabel(self.centralwidget)
        self.lsbslidernum5.setObjectName(u"lsbslidernum5")
        self.lsbslidernum5.setGeometry(QRect(580, 220, 16, 16))
        self.lsbslidernum5.setFont(font4)
        self.lsbslidernum5.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lsbslidernum5.setAlignment(Qt.AlignCenter)
        self.lsbslidernum5_2 = QLabel(self.centralwidget)
        self.lsbslidernum5_2.setObjectName(u"lsbslidernum5_2")
        self.lsbslidernum5_2.setGeometry(QRect(610, 220, 16, 16))
        self.lsbslidernum5_2.setFont(font4)
        self.lsbslidernum5_2.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lsbslidernum5_2.setAlignment(Qt.AlignCenter)
        self.lsbslidernum6 = QLabel(self.centralwidget)
        self.lsbslidernum6.setObjectName(u"lsbslidernum6")
        self.lsbslidernum6.setGeometry(QRect(640, 220, 16, 16))
        self.lsbslidernum6.setFont(font4)
        self.lsbslidernum6.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.lsbslidernum6.setAlignment(Qt.AlignCenter)
        self.LSBlabel = QLabel(self.centralwidget)
        self.LSBlabel.setObjectName(u"LSBlabel")
        self.LSBlabel.setGeometry(QRect(440, 170, 221, 21))
        self.LSBlabel.setFont(font2)
        self.LSBlabel.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.LSBlabel.setTextFormat(Qt.PlainText)
        self.LSBlabel.setAlignment(Qt.AlignCenter)
        self.LSBlabel.setWordWrap(False)
        self.LSBlabel.setMargin(0)
        self.LSBlabel.setIndent(0)
        QWidget.setTabOrder(self.comboBox, self.txtradioButton)
        QWidget.setTabOrder(self.txtradioButton, self.comboBox_2)
        QWidget.setTabOrder(self.comboBox_2, self.quitButton)
        QWidget.setTabOrder(self.quitButton, self.encodeButton)
        QWidget.setTabOrder(self.encodeButton, self.mp4radioButton)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Test GUI", None))
        self.titlelabel.setText(QCoreApplication.translate("MainWindow", u"LSB Encoder", None))
        self.quitButton.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.fileencodelabel.setText(QCoreApplication.translate("MainWindow", u"Select file to be encoded:", None))
        self.piclabel_3.setText(QCoreApplication.translate("MainWindow", u"Select Picture to be encoded to:", None))
        self.encodeButton.setText(QCoreApplication.translate("MainWindow", u"Encode!", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"example.txt", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"sample.mp4", None))
        self.comboBox.setItemText(2, "")

        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"Picture1.png", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Picture2.jpeg", None))

        self.label_before.setText("")
        self.originalpiclabel.setText(QCoreApplication.translate("MainWindow", u"Original Picture", None))
        self.encodedpiclabel.setText(QCoreApplication.translate("MainWindow", u"Encoded Picture", None))
        self.txtradioButton.setText(QCoreApplication.translate("MainWindow", u".txt file", None))
        self.mp4radioButton.setText(QCoreApplication.translate("MainWindow", u".mp4 file", None))
        self.DecodeButton.setText(QCoreApplication.translate("MainWindow", u"Decode!", None))
        self.lsbslidernum0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.lsbslidernum1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.lsbslidernum2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.lsbslidernum3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.lsbslidernum5.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.lsbslidernum5_2.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.lsbslidernum6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.LSBlabel.setText(QCoreApplication.translate("MainWindow", u"LSB Slider", None))
    # retranslateUi

